theKashey/react-focus-lock

- .eslintrc
- _tests/FocusLock.spec.js
- _tests/spinup/scaffolding.js
- package.json
- src/Lock.js
It actually introduces two things:
* Removes useless `if` statements from test file
We can use default mocha features for turning on/off test cases: [`.only`](https://mochajs.org/#exclusive-tests) and [`.skip`](https://mochajs.org/#inclusive-tests)
* Makes code compatible with eslint requirements
Let me know your thoughts about it, please.
> Make eslint happy and get rid of useless things

- _tests/FocusLock.spec.js
It is more obvious because we won't produce a code with warnings on the board.
It was started from #8 but I realized that in other test cases it may have other warnings. Now it will be clear.
> Force warnings in console fail test case

- src/Lock.js
When the focus guards steal focus, the browser* will automatically move the focused item into the viewport. Depending on how your modals are mounted, the focus guard could actually be somewhere in the middle (or even off the edges) of the viewport. Thus, when the focus guard is focused on, the content of the window appears offset.
This fixes the focus guard to the top left of the viewport so that the browser will never autoscroll even when the guards take focus.
*Actually only chrome does this
> Fix focusguards to top left of viewport

- src/Trap.js
Jest uses JSDom but by some reason without this fix I get:
```
/home/ai/Dev/amplifr-front/node_modules/react-focus-lock/dist/Trap.js:46
lastActiveFocus = document.activeElement;
^
TypeError: Cannot read property 'activeElement' of undefined
at Immediate.activateTrap (/home/ai/Dev/amplifr-front/node_modules/react-focus-lock/dist/Trap.js:46:34)
at runCallback (timers.js:773:18)
at tryOnImmediate (timers.js:734:5)
at processImmediate [as _immediateCallback] (timers.js:711:5)
```
> Fix Jest support

- package.json
- yarn.lock
I realised that the following test failed:
```
it('Should focus on inputs with tab indexes', (done) => {
const wrapper = mount(<div>
<div>
text
<button className="action1">action1</button>
text
</div>
<FocusLock>
<div>
text
<button className="action2-false" tabIndex={1} disabled>action2-false</button>
<button className="action2" tabIndex={1}>2-action2</button>
text
</div>
</FocusLock>
</div>, mountPoint);
wrapper.find('.action1').getDOMNode().focus();
expect(document.activeElement.innerHTML).to.be.equal('action1');
setTimeout(() => {
expect(document.activeElement.innerHTML).to.be.equal('2-action2');
done();
}, 10);
});
```
I updated the `focus-lock` library to the latest version and it fixed the failing test.
> Upgrading the focus-lock dependency from v0.5.2 to v0.5.4 to fix a failing test

- package.json
- yarn.lock
focus-lock version 0.6.4 makes use of `array.find`, which is stopping things from working in IE11
> update focus-lock dep to avoid array.find issue in ie11

- README.md
I struggled with restoring focus properly in `onDeactivation` for quite some time before I finally discovered https://github.com/theKashey/react-focus-lock/issues/12, which led me to the current note in README about setting a zero-timeout to properly restore focus.
I just added an example of what this looks like and linked to it from higher up in the doc.
In case it's helpful, here's a working example: https://codesandbox.io/s/crazy-wozniak-28h51
> Add README example for handling focus restoration on your own

- .size-limit.json
- UI/UI.d.ts
- _tests/FocusLock.spec.js
- interfaces.d.ts
- package.json
- react-focus-lock.d.ts
- src/Combination.js
- src/Lock.js
- yarn.lock
Allow ref forwarding, as well as refactor how components are composed inside.
Fixes: #88, #85
Breaks: #85 (ref become an object)
> feat: use forwardRef, and allow custom as prop

- README.md
I had to read the original 7 or 8 times to try and parse what it meant -- I believe this language makes the intent more clear (assuming I understood the original language correctly)
> Clear up AutoFocusInside language

- src/Trap.js
Avoid crash on IE. Only focusable elements have a blur() function on IE, so we can sometimes crash here without a check.
> fix: avoid crash on IE

- src/Combination.js
- src/Lock.js
#102 hoisted a problem, that all FocusLock components are just "ForwardRef".
Easy to fix
> Provide names for FocusLock components

- package.json
- yarn.lock
I'm seeing the following error the installing the current `react-focus-lock`
```
warning "react-focus-lock > react-clientside-effect@1.2.2" has incorrect peer dependency "react@^15.3.0 || ^16.0.0".
warning "react-focus-lock > use-callback-ref@1.2.1" has incorrect peer dependency "react@^16.8.0".
warning "react-focus-lock > use-sidecar@1.0.2" has incorrect peer dependency "react@^16.8.0".
```
after upgrading those, I think all of them support react 17 as peer dependency so the warning should go away 👍
> Upgrade some dependencies to remove warning when using react 17

- .circleci/config.yml
- package.json
- yarn.lock
Fixes https://github.com/theKashey/react-focus-lock/issues/162
@theKashey We would also need to bump the focus-lock version to fix the above issue.
> Update focus-lock version

- README.md
- src/Lock.js
A positive `tabIndex` has become a significant accessibility flag. The axe devtools bot flags any `tabIndex={1}` on your page as a serious error. Even though [this](https://github.com/theKashey/react-focus-lock/blob/4ef6569cd8be56b592a08ad951e84af4d0beaad6/src/Lock.js#L139) element with a `tabIndex` of `1` isn't really part of the direct user experience, it's best to get rid of any positive indices on your page. 
I found that when setting `noFocusGuards`, things worked fine when developing your storybook examples, but on my own setup this popped the focus out of the lock. 
As I understand the issue, the `tabIndex` value of `1` here handles cases when devs have other elements on their pages with a positive index.
It seems to me there would be two options:
- a backwards compatible prop …
> Remove positive tabIndex

- src/AutoFocusInside.js
Fixes a warning with react 18. See this issue.
https://github.com/theKashey/react-focus-lock/issues/239
> Remove default props in AutoFocusInside to fix react 18 warning

- interfaces.d.ts
The `children` property is optional in the `InFocusGuard` component. This updates the typescript interface so that it doesn't complain about children being required when we use `<InFocusGuard />`.
> Update InFocusGuard to make children prop optional

- CHANGELOG.md
- src/Trap.js
- src/util.js
Two actions are not in sync. As a solution:
- remove setImmediate, it does not really exists in browsers, but makes tests happy
- use the same defer helper for both cases.
> fix: correct crossframe behavior for Safari, fixes #249

- .eslintrc
- src/AutoFocusInside.js
- src/FocusGuard.js
- src/FreeFocusInside.js
- src/Lock.js
- src/MoveFocusInside.js
As default props on function components are going to be deprecated in future release in favor of default function parameters (see: https://github.com/facebook/react/pull/16210), I followed the recommendation. Note that default function parameters were actually already used (see `lockProps` for example)!
> Replace defaultProps with default function parameters

- src/Trap.js
- stories/Group.js
Originally reported by @alexzherdev - tests detected extra time spent at `expandFocusableNodes`
In fact, this code is only required for `auto-guards` (`<InFocusGuard/>`), so let's run it conditionally.
There is a supporting change at the focus-lock size - https://github.com/theKashey/focus-lock/commit/543b9fe9f379e5744f2b51046422b51cf390370c - speeding up nodes resolution
> fix: speedup resolution for auto-guards

- .size-limit.json
- README.md
- _tests/FocusLock.spec.js
- _tests/restore-focus.sidecar.spec.js
- package.json
- src/Lock.js
- src/Trap.js
- yarn.lock
Covers situations where return node does not exists
- records the "path" to the original node. And it should exist by the time of focus activation
- restores focus to the nearest sibling
> feat: smart return focus feature

- package.json
Hi! 
I'm using react-focus-lock in a project and I'm seeing this bug => https://github.com/theKashey/focus-lock/issues/68
It would be create if you could bump version.
Thanks in advance! 😊
> Bump focus-lock to 1.3.5

- .size-limit.json
- _tests/keep-focus.spec.js
- src/Lock.js
- src/Trap.js
- stories/Iframe.js
- if element is lost, restore focus
- if element is no longer focusable, restore focus
This change adds logic to "blur" event that triggers when focus moves to body.
In this case focus-lock will try to understand _why_ it happened and apply focus-restoration logic if applicable.
> fix: auto-focus in case of activeElement disappearance, fixes #321

- src/Trap.js
- stories/Exotic.js
- stories/index.js
There is a race conditions non reproducible via unit test where focus event can happen when the old and the new focus points at the body.
The focus restoration logic will try to "reset" itself, but will do it as many times, as many times body can be focused.
- applies only for `autoFocus:false` cases
> fix: correct focus order for non-autofocusable modals, fixes #340

- package.json
- yarn.lock
Fixes #351
As outlined there - not forcing the dependencies up to the latest version leads to situations where it still is incompatible:
```
└─┬ react-focus-lock 2.13.5
├─┬ react-clientside-effect 1.2.6
│ └── ✕ unmet peer react@"^15.3.0 || ^16.0.0 || ^17.0.0 || ^18.0.0": found 19.0.0
├─┬ use-callback-ref 1.3.2
│ ├── ✕ unmet peer react@"^16.8.0 || ^17.0.0 || ^18.0.0": found 19.0.0
│ └── ✕ unmet peer @types/react@"^16.8.0 || ^17.0.0 || ^18.0.0": found 19.0.7
└─┬ use-sidecar 1.1.2
├── ✕ unmet peer react@"^16.8.0 || ^17.0.0 || ^18.0.0": found 19.0.0
└── ✕ unmet peer @types/react@"^16.9.0 || ^17.0.0 || ^18.0.0": found 19.0.7
```
> fix: enforce react 19 compatible dependencies
